services:
  JobBoy\Process\Api\Controller\ProcessListController:
    class: JobBoy\Process\Api\Controller\ProcessListController
    arguments:
      - '@JobBoy\Process\Api\Security\RequiredRoleProvider'
      - '@JobBoy\Process\Application\Service\ListProcesses'
      - '@JobBoy\Process\Api\Normalizer\ProcessNormalizer'
    tags:
      - {name: 'controller.service_arguments'}
